sudo: required
services:
  - docker

before_install:
  - docker build -t josuels/github-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true josuels/github-travis npm run test

  # - docker run -e CI=true USERNAME/docker-react npm run test
